# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: ecosim-mysql-localstorage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: Immediate
# reclaimPolicy: Delete

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecosim-pv
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  local:
    path: /storage/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minwage-app
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecosim-mysql-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
