apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ecosim-mysql-localstorage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecosim-mysql-pvc
spec:
  storageClassName: ecosim-mysql-localstorage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
