apiVersion: v1
kind: Service
metadata:
  name: ecosim-redisdb-service
spec:
  clusterIP: None
  selector:
    app: ecosim-redisdb
  ports:
  - port: 6379
    targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosim-redisdb
spec:
  selector:
    matchLabels:
      app: ecosim-redisdb
  template:
    metadata:
      labels:
        app: ecosim-redisdb
    spec:
      containers:
      - name: redisdb
        image: redis:7.0.11
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 6379
