# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: print stuff
        run: echo "Testing first workflow"
        shell: bash
      - name: list all
        run:  ls
        shell: bash
